name: 'go-postgres'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env  
    ports:
      - 5432:5432

volumes:
  postgres-data:
